### ISSUE TITLE
tab character

### ISSUE THREAD

**Issue by maqdev** [neyestrabelli/xml-formatter#8]
readme says that tab's are possible but i didn't found how do I configure with tab character (have to put it into the sources like "\t"
Is there really a way to specify tab character in UI?

**Comment by TGOS** [comment]
You cannot enter a tab character into a text field. When you are in a text field and hit tab, the cursor jumps to the next tab field. So this setting is useless at the moment. Just make it a checkbox ("Use tab instead of spaces"), people will hardly ever want anything other than either tab or spaces (I prefer tabs because all editor apps today allow to dynamically make tabs appear as wide as I want them to be, while 4 spaces will always be 4 spaces wide). And please don't call the next option "Spaces indent" (that's a stupid name as first of all it may not be spaces and second of all it doesn't really say what this option is good for), call it something like "Number of indent characters per (indent) level" or the like.

**Comment by neyestrabelli** [comment]
@maqdev @TGOS in version 0.8.1 i add option to use tab instead of spaces.

Thanks by suggestion.

**Comment by maqdev** [comment]
:+1:
